# Generated by Django 3.1.2 on 2020-10-04 01:28

from django.db import migrations
from csvfile.models import StateInformation
from django.utils.dateparse import parse_date
import os
import csv

def load_csv(apps, schema_editor):
    current_dir = os.path.dirname(os.path.abspath(__file__))
    with open(os.path.join(current_dir, 'voting_info.csv'), newline='') as csvfile:
        for column in csv.reader(csvfile, delimiter=',', quotechar='"'):
            _, created = StateInformation.objects.update_or_create(
                name = column[0],
                ip_reg_deadline = parse_date(column[1]),
                mail_reg_deadline = parse_date(column[2]),
                reg_post_or_rec = column[3],
                online_reg_deadline = parse_date(column[4]),
                is_mail_limits = column[5],
                is_covid_changes = column[6],
                covid_change = column[7],
                ip_req_deadline = parse_date(column[8]),
                online_req_dealine = parse_date(column[9]),
                mail_request_deadline = parse_date(column[10]),
                req_post_or_rec = column[11],
                reg_url = column[12],
                reg_status_url = column[13],
                reg_update_url = column[14],
                is_doc_req = column[15],
                req_doc = column[16],
                req_url = column[17],
                ip_return_deadline = parse_date(column[18]),
                mail_return_deadline = parse_date(column[19]),
                return_post_or_rec = column[20],
                notary_or_witness = column[21],
                signiture_req = column[22]
            )
    
class Migration(migrations.Migration):

    dependencies = [
        ('csvfile', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_csv),
    ]