# Generated by Django 3.1.2 on 2020-10-04 05:10

from django.db import migrations
from home.models import state_key
import os
import csv

def make_keys(apps, schema_editor):
    current_dir = os.path.dirname(os.path.abspath(__file__))
    with open(os.path.join(current_dir, 'State_Abr.csv'), newline='') as csvfile:
        for column in csv.reader(csvfile, delimiter=',', quotechar='"'):
            _, created = state_key.objects.update_or_create(
                name = column[0],
                abbreviation = column[1]
            )

class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(make_keys),
    ]
